apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-servico
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meu-servico
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: meu-servico
        version: "v2-problematica"
    spec:
      containers:
      - name: meu-servico-container
        image: linuxtips/memory-eater:0.3
        resources:
          limits:
            memory: 32Mi